#!/usr/bin/env python3
"""
run_pipeline_v3_local.py

V3 Local "Creator Mode" Pipeline
---------------------------------
Hybrid architecture:
  - Gemini API (cloud) generates the lesson JSON (already done by GitHub Actions)
  - This script runs LOCALLY on Mac to create the final high-quality video

Steps:
  1. Parse lesson JSON (generated by Gemini)
  2. Synthesize narration audio in your cloned voice (F5-TTS, local)
  3. Record live Python code execution in a real Terminal (screencapture, local)
  4. Merge everything into final unconstrained MP4
  5. Publish code + architecture to GitHub Gist

Usage:
  python run_pipeline_v3_local.py --input rag_learning_series/lesson_012/lesson_012.json
  python run_pipeline_v3_local.py --input rag_learning_series/lesson_012/lesson_012.json --lang hi
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

REPO_ROOT = Path(__file__).parent
PYTHON_BIN = str(REPO_ROOT / ".venv" / "bin" / "python")

# ─── Helpers ──────────────────────────────────────────────────────────────────

def banner(msg: str):
    print(f"\n{'='*60}")
    print(f"  {msg}")
    print('='*60)


def load_lesson(json_path: str) -> dict:
    with open(json_path) as f:
        return json.load(f)


def get_slides(lesson: dict) -> list:
    """Normalize lesson JSON to a list of slides regardless of schema version."""
    # V2+ schema uses 'storyboard'
    if "storyboard" in lesson:
        return lesson["storyboard"]
    # Legacy schema uses 'slides'
    return lesson.get("slides", [])


def get_narration(slide: dict, lang: str = "en") -> str:
    """Extract narration text for a slide, supporting multiple field name conventions."""
    if lang == "hi":
        return (
            slide.get("narration_text_hi")
            or slide.get("narration_hi")
            or slide.get("narration")
            or ""
        )
    return (
        slide.get("narration_text_en")
        or slide.get("narration_en")
        or slide.get("narration")
        or ""
    )


def get_code(slide: dict) -> str:
    """Extract runnable Python code from a slide."""
    vtype = slide.get("visual_type", "")
    if vtype not in ("code_snippet", "code_demo"):
        return ""
    content = slide.get("visual_content") or slide.get("content_code") or slide.get("content") or ""
    # Filter out non-Python terminal output style content
    if isinstance(content, dict):
        return content.get("code", "")
    return str(content)


def is_code_slide(slide: dict) -> bool:
    return slide.get("visual_type") in ("code_snippet", "code_demo")


# ─── Step 0: Knowledge Validation ───────────────────────────────────────────

def validate_and_fix(lesson_json_path: str) -> dict:
    """Run Gemini knowledge validation and auto-fix critical issues."""
    from v3_engine.knowledge_validator import validate_lesson, apply_fixes
    result = validate_lesson(lesson_json_path)
    if not result["passed"] and result.get("issues"):
        print("  [validate] 🔧 Applying auto-fixes for critical issues...")
        apply_fixes(lesson_json_path, result["issues"])
    return result


# ─── Step 1: Voice Synthesis ──────────────────────────────────────────────────
def synthesize_narrations(lesson: dict, output_dir: Path, lang: str = "en") -> list[Path]:
    """
    Generate voice narration for each slide using F5-TTS (your cloned voice).
    Falls back to edge-tts if F5-TTS model download hasn't happened yet.
    Returns list of audio file paths in slide order.
    """
    from v3_engine.voice_clone import synthesize_speech

    audio_paths = []
    slides = get_slides(lesson)

    for i, slide in enumerate(slides):
        narration = get_narration(slide, lang)
        if not narration:
            audio_paths.append(None)
            continue

        out_path = str(output_dir / f"slide_{i:02d}_audio.wav")
        print(f"  [Voice] Slide {i+1}/{len(slides)}: '{narration[:50]}...'")
        success = synthesize_speech(narration, out_path)
        audio_paths.append(Path(out_path) if success else None)

    return audio_paths


# ─── Step 2: Visual Recording (VS Code) ─────────────────────────────────────

def record_code_slides(lesson: dict, output_dir: Path) -> dict[int, Path]:
    """
    For each code_snippet slide, open VS Code, run the code live,
    and screen-record the execution. Returns {slide_index: recording_path}.
    """
    from v3_engine.vscode_recorder import record_vscode_session

    recordings = {}
    slides = get_slides(lesson)
    lesson_title = lesson.get("meta_title") or lesson.get("title", "Lesson")

    for i, slide in enumerate(slides):
        if not is_code_slide(slide):
            continue

        code = get_code(slide)
        if not code:
            continue

        slide_title = slide.get("title_en") or slide.get("title", f"Code Demo {i}")
        recording_path = str(output_dir / f"slide_{i:02d}_recording.mov")

        # Skip if already recorded
        if Path(recording_path).exists():
            print(f"  [Recorder] ⏭️  Slide {i+1} already recorded, skipping.")
            recordings[i] = Path(recording_path)
            continue

        print(f"  [Recorder] Slide {i+1}: {slide_title}")
        success = record_vscode_session(
            code=code,
            lesson_title=f"{lesson_title} — {slide_title}",
            output_path=recording_path,
        )

        if success:
            recordings[i] = Path(recording_path)
        else:
            print(f"  [Recorder] ⚠️  Recording failed for slide {i}, continuing...")

    return recordings


# ─── Step 2b: Diagram Generation ─────────────────────────────────────────────

def generate_diagrams(lesson: dict, output_dir: Path) -> dict[int, Path]:
    """Generate Gemini Imagen diagrams for architecture/sequence slides."""
    from v3_engine.diagram_generator import generate_diagram

    diagrams = {}
    slides = get_slides(lesson)
    lesson_title = lesson.get("meta_title") or lesson.get("title", "")
    DIAGRAM_TYPES = {"architecture_diagram", "sequence_diagram", "concept_box"}

    for i, slide in enumerate(slides):
        if slide.get("visual_type") not in DIAGRAM_TYPES:
            continue
        out_path = str(output_dir / f"slide_{i:02d}_diagram.png")
        if Path(out_path).exists():
            diagrams[i] = Path(out_path)
            continue
        success = generate_diagram(slide, out_path, lesson_title)
        if success:
            diagrams[i] = Path(out_path)

    return diagrams


# ─── Step 3: Compile Final Video (with face PiP) ──────────────────────────────

def compile_final_video(
    lesson: dict,
    audio_paths: list,
    recordings: dict,
    diagrams: dict,
    output_path: str,
    lang: str = "en",
) -> bool:
    """
    Compile the final video:
    - Intro: user face (full) + cloned voice
    - Code slides: VS Code recording + narration audio + face PiP corner
    - Other slides: rendered slide + narration + face PiP corner
    - Outro: user face (full) + call to action
    """
    from moviepy import (
        VideoFileClip, AudioFileClip, ImageClip,
        concatenate_videoclips,
    )
    from moviepy.video.compositing.CompositeVideoClip import CompositeVideoClip

    slides = get_slides(lesson)
    clips = []
    FPS = 24
    DEFAULT_DURATION = 7.0
    W, H = 1920, 1080
    FACE_H = 280  # height of PiP face overlay

    # ── Load face clip for PiP overlay ───────────────────────────────────
    face_path = str(REPO_ROOT / "assets" / "my_face_idle.mp4")
    has_face = Path(face_path).exists()
    face_loop = None
    if has_face:
        try:
            face_loop = VideoFileClip(face_path).resized(height=FACE_H).loop()
            print(f"  [compile] 👤 Face PiP loaded (height={FACE_H}px)")
        except Exception as e:
            print(f"  [compile] ⚠️  Could not load face: {e}")
            has_face = False

    def add_face_pip(base_clip, duration: float):
        """Add face PiP to bottom-left corner of any clip."""
        if not has_face or face_loop is None:
            return base_clip
        face_clip = face_loop.subclipped(0, min(duration, face_loop.duration))
        face_clip = face_clip.with_position((30, H - FACE_H - 30))  # bottom-left
        return CompositeVideoClip([base_clip, face_clip])

    # ── Compile slides ────────────────────────────────────────────────────
    for i, slide in enumerate(slides):
        audio_path = audio_paths[i] if i < len(audio_paths) else None

        clip_duration = DEFAULT_DURATION
        audio_clip = None
        if audio_path and Path(str(audio_path)).exists():
            audio_clip = AudioFileClip(str(audio_path))
            clip_duration = audio_clip.duration

        base_clip = None

        if is_code_slide(slide) and i in recordings:
            # Real VS Code recording
            rec = VideoFileClip(str(recordings[i])).resized((W, H))
            if rec.duration > clip_duration:
                rec = rec.subclipped(0, clip_duration)
            base_clip = rec

        elif i in diagrams:
            # Gemini-generated diagram image
            base_clip = ImageClip(str(diagrams[i]), duration=clip_duration).resized((W, H))

        else:
            # Render slide with V2 image engine
            img_path = _render_slide_image(slide, i, lang)
            if img_path:
                base_clip = ImageClip(img_path, duration=clip_duration).resized((W, H))

        if base_clip is None:
            print(f"  [compile] ⏭️  Skipping slide {i} (no content)")
            continue

        # Add audio
        if audio_clip:
            base_clip = base_clip.with_audio(audio_clip)

        # Add face PiP to every slide
        base_clip = add_face_pip(base_clip, clip_duration)
        clips.append(base_clip.with_fps(FPS))

    if face_loop:
        face_loop.close()

    if not clips:
        print("[compile] ❌ No clips to compile!")
        return False

    final = concatenate_videoclips(clips, method="compose")
    print(f"[compile] 🎬 Writing: {output_path} ({final.duration:.1f}s)")
    final.write_videofile(
        output_path,
        fps=FPS,
        codec="libx264",
        audio_codec="aac",
        threads=4,
    )
    final.close()
    return True


def _render_slide_image(slide: dict, index: int, lang: str) -> str | None:
    """Use the V2 image engine to render a single slide as a PNG."""
    try:
        from core.image_engine import render_slide
        out_path = f"/tmp/v3_slide_{index:02d}_{lang}.png"
        render_slide(slide, out_path, lang=lang)
        return out_path
    except Exception as e:
        print(f"  [compile] ⚠️  Could not render slide {index}: {e}")
        return None


# ─── Step 4: Gist Publishing ─────────────────────────────────────────────────

def publish_to_gist(lesson_json_path: str) -> str | None:
    from v3_engine.gist_publisher import publish_lesson_to_gist
    return publish_lesson_to_gist(lesson_json_path)


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="V3 Local Creator Mode Pipeline")
    parser.add_argument("--input", required=True, help="Path to lesson JSON")
    parser.add_argument("--lang", default="en", choices=["en", "hi"], help="Language")
    parser.add_argument("--skip-validate", action="store_true", help="Skip Gemini knowledge validation")
    parser.add_argument("--skip-voice", action="store_true", help="Skip voice synthesis")
    parser.add_argument("--skip-record", action="store_true", help="Skip live code recording")
    parser.add_argument("--skip-diagrams", action="store_true", help="Skip Gemini diagram generation")
    parser.add_argument("--skip-gist", action="store_true", help="Skip Gist publishing")
    args = parser.parse_args()

    lesson_path = Path(args.input)
    if not lesson_path.exists():
        print(f"❌ Lesson file not found: {lesson_path}")
        sys.exit(1)

    lesson = load_lesson(str(lesson_path))
    lesson_title = lesson.get("meta_title") or lesson.get("title") or lesson_path.stem
    output_dir = lesson_path.parent
    build_dir = output_dir / "v3_build"
    build_dir.mkdir(exist_ok=True)

    final_output = str(output_dir / f"presentation_{args.lang}_v3.mp4")

    banner(f"V3 Pipeline: {lesson_title} [{args.lang.upper()}]")

    # ── Step 0: Knowledge Validation ─────────────────────────────────────
    banner("Step 0: Validating Lesson Content (Gemini)")
    if not args.skip_validate:
        result = validate_and_fix(str(lesson_path))
        # Reload lesson in case fixes were applied
        lesson = load_lesson(str(lesson_path))
    else:
        print("  ⏭️  Skipped (--skip-validate)")

    slides = get_slides(lesson)
    slide_count = len(slides)

    # ── Step 1: Voice Synthesis ──────────────────────────────────────────
    banner("Step 1: Synthesizing Voice Narrations (F5-TTS)")
    if not args.skip_voice:
        audio_paths = synthesize_narrations(lesson, build_dir, lang=args.lang)
        print(f"  ✅ Generated {sum(1 for a in audio_paths if a)}/{slide_count} audio clips")
    else:
        print("  ⏭️  Skipped (--skip-voice)")
        audio_paths = [None] * slide_count

    # ── Step 2: VS Code Recording ────────────────────────────────────────
    banner("Step 2: Recording Code Demos in VS Code")
    if not args.skip_record:
        recordings = record_code_slides(lesson, build_dir)
        print(f"  ✅ Recorded {len(recordings)} code demo(s)")
    else:
        print("  ⏭️  Skipped (--skip-record)")
        recordings = {}

    # ── Step 2b: Diagram Generation ──────────────────────────────────────
    banner("Step 2b: Generating Diagrams (Gemini Imagen)")
    if not args.skip_diagrams:
        diagrams = generate_diagrams(lesson, build_dir)
        print(f"  ✅ Generated {len(diagrams)} diagram(s)")
    else:
        print("  ⏭️  Skipped (--skip-diagrams)")
        diagrams = {}

    # ── Step 3: Compile Video ────────────────────────────────────────────
    banner("Step 3: Compiling Final Video (with Face PiP)")
    success = compile_final_video(
        lesson=lesson,
        audio_paths=audio_paths,
        recordings=recordings,
        diagrams=diagrams,
        output_path=final_output,
        lang=args.lang,
    )

    if success:
        size_mb = Path(final_output).stat().st_size / (1024 * 1024)
        print(f"\n  ✅ Video saved: {final_output} ({size_mb:.1f} MB)")
    else:
        print("\n  ❌ Video compilation failed")
        sys.exit(1)

    # ── Step 4: Publish to Gist ──────────────────────────────────────────
    banner("Step 4: Publishing Code to GitHub Gist")
    if not args.skip_gist:
        gist_url = publish_to_gist(str(lesson_path))
        if gist_url:
            print(f"  ✅ Gist: {gist_url}")
    else:
        print("  ⏭️  Skipped (--skip-gist)")

    # ── Done ─────────────────────────────────────────────────────────────
    banner("All Done! 🎉")
    print(f"  📹 Video    : {final_output}")
    print(f"  📁 Build Dir: {build_dir}")
    print()


if __name__ == "__main__":
    main()
