#!/usr/bin/env python3
"""
run_pipeline_v3_local.py

V3 Local "Creator Mode" Pipeline
---------------------------------
Hybrid architecture:
  - Gemini API (cloud) generates the lesson JSON (already done by GitHub Actions)
  - This script runs LOCALLY on Mac to create the final high-quality video

Steps:
  1. Parse lesson JSON (generated by Gemini)
  2. Synthesize narration audio in your cloned voice (F5-TTS, local)
  3. Record live Python code execution in a real Terminal (screencapture, local)
  4. Merge everything into final unconstrained MP4
  5. Publish code + architecture to GitHub Gist

Usage:
  python run_pipeline_v3_local.py --input rag_learning_series/lesson_012/lesson_012.json
  python run_pipeline_v3_local.py --input rag_learning_series/lesson_012/lesson_012.json --lang hi
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

REPO_ROOT = Path(__file__).parent
PYTHON_BIN = str(REPO_ROOT / ".venv" / "bin" / "python")

# ─── Helpers ──────────────────────────────────────────────────────────────────

def banner(msg: str):
    print(f"\n{'='*60}")
    print(f"  {msg}")
    print('='*60)


def load_lesson(json_path: str) -> dict:
    with open(json_path) as f:
        return json.load(f)


# ─── Step 1: Voice Synthesis ──────────────────────────────────────────────────

def synthesize_narrations(lesson: dict, output_dir: Path, lang: str = "en") -> list[Path]:
    """
    Generate voice narration for each slide using F5-TTS (your cloned voice).
    Falls back to edge-tts if F5-TTS model download hasn't happened yet.
    Returns list of audio file paths in slide order.
    """
    from v3_engine.voice_clone import synthesize_speech

    audio_paths = []
    slides = lesson.get("slides", [])

    for i, slide in enumerate(slides):
        narration = slide.get("narration_hi" if lang == "hi" else "narration", "")
        if not narration:
            narration = slide.get("narration", "")

        if not narration:
            audio_paths.append(None)
            continue

        out_path = str(output_dir / f"slide_{i:02d}_audio.wav")
        print(f"  [Voice] Slide {i+1}/{len(slides)}: '{narration[:50]}...'")
        success = synthesize_speech(narration, out_path)
        audio_paths.append(Path(out_path) if success else None)

    return audio_paths


# ─── Step 2: Live Code Recording ─────────────────────────────────────────────

def record_code_slides(lesson: dict, output_dir: Path) -> dict[int, Path]:
    """
    For each code_demo slide, open a Terminal window, run the code live,
    and screen-record the execution. Returns {slide_index: recording_path}.
    """
    from v3_engine.live_recorder import record_code_execution

    recordings = {}
    slides = lesson.get("slides", [])
    lesson_title = lesson.get("title", "Lesson")

    for i, slide in enumerate(slides):
        if slide.get("type") != "code_demo":
            continue

        code = slide.get("content", "")
        if not code:
            continue

        slide_title = slide.get("title", f"Code Demo {i}")
        recording_path = str(output_dir / f"slide_{i:02d}_recording.mov")

        print(f"  [Recorder] Slide {i+1}: {slide_title}")
        success = record_code_execution(
            code=code,
            lesson_title=f"{lesson_title} — {slide_title}",
            output_path=recording_path,
            python_bin=PYTHON_BIN,
        )

        if success:
            recordings[i] = Path(recording_path)
        else:
            print(f"  [Recorder] ⚠️  Recording failed for slide {i}, continuing...")

    return recordings


# ─── Step 3: Compile Final Video ─────────────────────────────────────────────

def compile_final_video(
    lesson: dict,
    audio_paths: list,
    recordings: dict,
    output_path: str,
    lang: str = "en",
) -> bool:
    """
    Compile the final video by merging:
    - For code slides: the live terminal recording + narration audio
    - For other slides: rendered slide image + narration audio (V2 style)
    """
    from moviepy import (
        VideoFileClip, AudioFileClip, ImageClip,
        concatenate_videoclips,
    )

    slides = lesson.get("slides", [])
    clips = []
    FPS = 24

    for i, slide in enumerate(slides):
        audio_path = audio_paths[i] if i < len(audio_paths) else None
        slide_type = slide.get("type", "")

        # Get audio duration to know clip length
        clip_duration = 6.0  # default
        audio_clip = None
        if audio_path and audio_path.exists():
            audio_clip = AudioFileClip(str(audio_path))
            clip_duration = audio_clip.duration

        if slide_type == "code_demo" and i in recordings:
            # Use the real terminal recording
            rec_path = recordings[i]
            video_clip = VideoFileClip(str(rec_path)).resized((1920, 1080))

            # Trim/pad to match audio duration
            if video_clip.duration > clip_duration:
                video_clip = video_clip.subclipped(0, clip_duration)

            if audio_clip:
                video_clip = video_clip.with_audio(audio_clip)

            clips.append(video_clip)
        else:
            # Render slide using V2 compiler for non-code slides
            slide_img_path = _render_slide_image(slide, i, lang)
            if slide_img_path:
                img_clip = ImageClip(slide_img_path, duration=clip_duration)
                if audio_clip:
                    img_clip = img_clip.with_audio(audio_clip)
                clips.append(img_clip)

    if not clips:
        print("[compile] ❌ No clips to compile!")
        return False

    final = concatenate_videoclips(clips, method="compose")
    print(f"[compile] 🎬 Writing final video: {output_path}")
    print(f"[compile]    Total duration: {final.duration:.1f}s")

    final.write_videofile(
        output_path,
        fps=FPS,
        codec="libx264",
        audio_codec="aac",
        threads=4,
    )
    final.close()
    return True


def _render_slide_image(slide: dict, index: int, lang: str) -> str | None:
    """Use the V2 image engine to render a single slide as a PNG."""
    try:
        from core.image_engine import render_slide
        out_path = f"/tmp/v3_slide_{index:02d}_{lang}.png"
        render_slide(slide, out_path, lang=lang)
        return out_path
    except Exception as e:
        print(f"  [compile] ⚠️  Could not render slide {index}: {e}")
        return None


# ─── Step 4: Gist Publishing ─────────────────────────────────────────────────

def publish_to_gist(lesson_json_path: str) -> str | None:
    from v3_engine.gist_publisher import publish_lesson_to_gist
    return publish_lesson_to_gist(lesson_json_path)


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="V3 Local Creator Mode Pipeline")
    parser.add_argument("--input", required=True, help="Path to lesson JSON")
    parser.add_argument("--lang", default="en", choices=["en", "hi"], help="Language")
    parser.add_argument("--skip-voice", action="store_true", help="Skip voice synthesis (use edge-tts)")
    parser.add_argument("--skip-record", action="store_true", help="Skip live code recording")
    parser.add_argument("--skip-gist", action="store_true", help="Skip Gist publishing")
    args = parser.parse_args()

    lesson_path = Path(args.input)
    if not lesson_path.exists():
        print(f"❌ Lesson file not found: {lesson_path}")
        sys.exit(1)

    lesson = load_lesson(str(lesson_path))
    lesson_title = lesson.get("title", lesson_path.stem)
    output_dir = lesson_path.parent
    build_dir = output_dir / "v3_build"
    build_dir.mkdir(exist_ok=True)

    final_output = str(output_dir / f"presentation_{args.lang}_v3.mp4")

    banner(f"V3 Pipeline: {lesson_title} [{args.lang.upper()}]")

    # ── Step 1: Voice Synthesis ──────────────────────────────────────────
    banner("Step 1: Synthesizing Voice Narrations")
    if not args.skip_voice:
        audio_paths = synthesize_narrations(lesson, build_dir, lang=args.lang)
        print(f"  ✅ Generated {sum(1 for a in audio_paths if a)} audio clips")
    else:
        print("  ⏭️  Skipped (--skip-voice)")
        audio_paths = [None] * len(lesson.get("slides", []))

    # ── Step 2: Live Code Recording ──────────────────────────────────────
    banner("Step 2: Recording Live Code Execution")
    if not args.skip_record:
        recordings = record_code_slides(lesson, build_dir)
        print(f"  ✅ Recorded {len(recordings)} code demo(s)")
    else:
        print("  ⏭️  Skipped (--skip-record)")
        recordings = {}

    # ── Step 3: Compile Video ────────────────────────────────────────────
    banner("Step 3: Compiling Final Video")
    success = compile_final_video(
        lesson=lesson,
        audio_paths=audio_paths,
        recordings=recordings,
        output_path=final_output,
        lang=args.lang,
    )

    if success:
        size_mb = Path(final_output).stat().st_size / (1024 * 1024)
        print(f"\n  ✅ Video saved: {final_output} ({size_mb:.1f} MB)")
    else:
        print("\n  ❌ Video compilation failed")
        sys.exit(1)

    # ── Step 4: Publish to Gist ──────────────────────────────────────────
    banner("Step 4: Publishing Code to GitHub Gist")
    if not args.skip_gist:
        gist_url = publish_to_gist(str(lesson_path))
        if gist_url:
            print(f"  ✅ Gist: {gist_url}")
    else:
        print("  ⏭️  Skipped (--skip-gist)")

    # ── Done ─────────────────────────────────────────────────────────────
    banner("All Done! 🎉")
    print(f"  📹 Video    : {final_output}")
    print(f"  📁 Build Dir: {build_dir}")
    print()


if __name__ == "__main__":
    main()
