"""
v3_engine/diagram_generator.py

Replaces mermaid .mmd diagram files with high-quality PNG diagrams
generated by Gemini's image generation capabilities.

For architecture slides, this creates visually rich, professional-looking
diagrams that are far better than the SVG mermaid output.
"""

import json
import os
import re
from pathlib import Path

import google.generativeai as genai

REPO_ROOT = Path(__file__).parent.parent


def generate_diagram(slide: dict, output_path: str, lesson_title: str = "") -> bool:
    """
    Generate a diagram PNG for an architecture/sequence slide using Gemini.

    Falls back to rendering the mermaid .mmd file if image generation fails.

    Args:
        slide: The slide dict from the storyboard.
        output_path: Where to save the diagram PNG.
        lesson_title: Used for context in the prompt.

    Returns:
        True if diagram was generated successfully.
    """
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        print("[diagram_generator] ⚠️  No GEMINI_API_KEY — skipping diagram generation.")
        return False

    slide_title = slide.get("title_en") or slide.get("title", "Architecture Diagram")
    visual_content = slide.get("visual_content", "")
    content_text = slide.get("content_text_en") or slide.get("content_text", "")

    # Determine what kind of diagram to generate
    visual_type = slide.get("visual_type", "")
    if visual_type == "sequence_diagram":
        diagram_style = "sequence/flow diagram showing steps and interactions"
    elif visual_type == "architecture_diagram":
        diagram_style = "system architecture diagram"
    else:
        diagram_style = "technical diagram"

    print(f"[diagram_generator] 🎨 Generating {diagram_style}: {slide_title}")

    # Build context from slide content
    context = ""
    if isinstance(visual_content, str):
        context = visual_content[:500]
    elif isinstance(visual_content, dict):
        context = json.dumps(visual_content)[:500]

    # Try Gemini image generation (Imagen)
    try:
        from google import genai as google_genai
        from google.genai import types

        client = google_genai.Client(api_key=api_key)

        prompt = (
            f"Create a clean, professional, dark-themed technical {diagram_style} for an AI/ML educational video. "
            f"Topic: '{slide_title}' from the lesson '{lesson_title}'. "
            f"Content context: {content_text[:300]}. "
            f"Diagram details: {context}. "
            f"Style: dark background (#0d1117), bright accent colors (cyan, purple, green), "
            f"clear arrows and labels, modern minimalist look suitable for a YouTube tech tutorial. "
            f"No text outside the diagram. High resolution, 16:9 aspect ratio."
        )

        result = client.models.generate_image(
            model="imagen-3.0-generate-002",
            prompt=prompt,
            config=types.GenerateImageConfig(
                number_of_images=1,
                aspect_ratio="16:9",
                output_mime_type="image/png",
            ),
        )

        if result.generated_images:
            img_data = result.generated_images[0].image.image_bytes
            with open(output_path, "wb") as f:
                f.write(img_data)
            print(f"[diagram_generator] ✅ Saved to {output_path}")
            return True

    except Exception as e:
        print(f"[diagram_generator] ⚠️  Imagen failed: {e}. Trying mermaid fallback...")

    # Fallback: render existing .mmd file if it exists
    return _render_mmd_fallback(slide, output_path)


def _render_mmd_fallback(slide: dict, output_path: str) -> bool:
    """
    Render the mermaid diagram from the exports/ directory as a PNG fallback.
    Uses mermaid-js CLI (mmdc) if installed, otherwise returns False.
    """
    # Find any .mmd file in exports/ matching this slide
    exports_dir = REPO_ROOT / "rag_learning_series"
    mmd_files = list(exports_dir.rglob("*.mmd"))
    if not mmd_files:
        return False

    # Pick first mmd file as fallback
    mmd_file = mmd_files[0]
    print(f"[diagram_generator] 📄 Trying mermaid fallback: {mmd_file.name}")

    try:
        import subprocess
        result = subprocess.run(
            ["npx", "-y", "@mermaid-js/mermaid-cli", "-i", str(mmd_file), "-o", output_path,
             "-b", "#0d1117", "-t", "dark", "--width", "1920", "--height", "1080"],
            capture_output=True, timeout=30
        )
        if result.returncode == 0 and Path(output_path).exists():
            print(f"[diagram_generator] ✅ Mermaid PNG saved: {output_path}")
            return True
    except Exception as e:
        print(f"[diagram_generator] ❌ Mermaid fallback failed: {e}")

    return False


def generate_thumbnail(
    lesson_title: str,
    lesson_id: str,
    face_image_path: str,
    output_path: str,
) -> bool:
    """
    Generate a YouTube thumbnail using Gemini Imagen.
    Combines: lesson title + visual channel branding + avatar.

    Args:
        lesson_title: e.g. "Build a RAG Pipeline in Python"
        lesson_id: e.g. "lesson_012"
        face_image_path: Path to a frame of the user's face (used as style reference)
        output_path: Where to save the thumbnail PNG.

    Returns:
        True if thumbnail was generated.
    """
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        print("[thumbnail] ⚠️  No API key — skipping thumbnail generation.")
        return False

    print(f"[thumbnail] 🖼️  Generating YouTube thumbnail for: {lesson_title}")

    try:
        from google import genai as google_genai
        from google.genai import types

        client = google_genai.Client(api_key=api_key)

        prompt = (
            f"Create a professional YouTube thumbnail for a video titled: '{lesson_title}'. "
            f"Channel name: 'Understanding AIML'. "
            f"Style: dark background, neon/glowing text, tech aesthetic, "
            f"include visual elements like Python code snippets, neural network nodes, or RAG pipeline arrows. "
            f"Bold readable title text prominently featured. "
            f"High energy, modern tech YouTube thumbnail style. "
            f"Leave space on the right side for a portrait photo overlay. "
            f"16:9 aspect ratio, 1280x720 resolution."
        )

        result = client.models.generate_image(
            model="imagen-3.0-generate-002",
            prompt=prompt,
            config=types.GenerateImageConfig(
                number_of_images=1,
                aspect_ratio="16:9",
                output_mime_type="image/png",
            ),
        )

        if result.generated_images:
            img_data = result.generated_images[0].image.image_bytes
            with open(output_path, "wb") as f:
                f.write(img_data)
            print(f"[thumbnail] ✅ Thumbnail saved: {output_path}")
            return True

    except Exception as e:
        print(f"[thumbnail] ❌ Failed: {e}")

    return False


if __name__ == "__main__":
    # Test thumbnail generation
    import sys
    title = sys.argv[1] if len(sys.argv) > 1 else "Build a RAG Pipeline in Python"
    out = "/tmp/test_thumbnail.png"
    success = generate_thumbnail(
        lesson_title=title,
        lesson_id="lesson_012",
        face_image_path="assets/my_face_idle.mp4",
        output_path=out,
    )
    print(f"Result: {'✅' if success else '❌'} — {out}")
